"""Add Like model

Revision ID: 331b0fd667cf
Revises: b509b406b94c
Create Date: 2025-08-18 20:47:01.081227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331b0fd667cf'
down_revision: Union[str, Sequence[str], None] = 'b509b406b94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interests', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('interests', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interests', 'deleted_at')
    op.drop_column('interests', 'is_deleted')
    # ### end Alembic commands ###
