"""add interests and user-interest association

Revision ID: c6147a5566d9
Revises: bfd3ef94b22a
Create Date: 2025-08-03 10:50:25.126390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6147a5566d9'
down_revision: Union[str, Sequence[str], None] = 'bfd3ef94b22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interest_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    op.drop_table('user_interest')
    op.alter_column('interests', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interests', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('user_interest',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('user_interest_interest_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_interest_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'interest_id', name=op.f('user_interest_pkey'))
    )
    op.drop_table('user_interest_association')
    # ### end Alembic commands ###
