"""обавлен никнейм в User

Revision ID: 2aa22bc0ef31
Revises: 291d2e8a5125
Create Date: 2025-08-06 23:02:34.300547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa22bc0ef31'
down_revision: Union[str, Sequence[str], None] = '291d2e8a5125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_type', sa.String(), nullable=False))
    op.create_unique_constraint('unique_chat', 'chats', ['user1_id', 'user2_id', 'chat_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_chat', 'chats', type_='unique')
    op.drop_column('chats', 'chat_type')
    # ### end Alembic commands ###
